// <auto-generated />
namespace eUseControl.BusinessLogic.Migrations.Cart
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IntegrateCartItemsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntegrateCartItemsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202505192158005_IntegrateCartItemsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
