// <auto-generated />
namespace eUseControl.BusinessLogic.Migrations.Wishlist
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IntegrateWishlistProductsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntegrateWishlistProductsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202505181532184_IntegrateWishlistProductsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
