// <auto-generated />
namespace eUseControl.BusinessLogic.Migrations.Coupon
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IntegrateDiscountCouponsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntegrateDiscountCouponsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202505210752428_IntegrateDiscountCouponsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
