// <auto-generated />
namespace eUseControl.BusinessLogic.Migrations.Products
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IntegrateProductsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntegrateProductsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202505070935331_IntegrateProductsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
